package it.prova.prenotazioni.model;

public enum Tipo {

	CAMERA_SINGOLA, CAMERA_DOPPIA, CAMERA_MATRIMONIALE, SUITE, JUNIOR_SUITE, CAMERA_TRIPLA, CAMERA_QUADRUPLA,
	CAMERA_FAMILIARE, CAMERA_DELUXE, CAMERA_SUPERIOR, CAMERA_ECONOMICA, CAMERA_CON_VISTA, CAMERA_ACCESSIBILE,
	CAMERA_ATTICO, CAMERA_BUSINESS, CAMERA_STANDARD, CAMERA_LUSSO, CAMERA_CON_BALCONE, CAMERA_CON_TERRAZZA,
	CAMERA_EXECUTIVE
}
